### ISSUE TITLE
csharp_new_line_before_open_brace Not Working

### ISSUE THREAD

**Issue by RehanSaeed** [madskristensen/EditorConfigLanguage#11]
### Installed product versions
- Visual Studio: 2017
- This extension: 1.16.198

### Description
The csharp_new_line_before_open_brace setting seems stuck on `all`. I was going to raise this in the roslyn repo but thought it might be a tooling issue in VS 2017.

### Steps to recreate
1. Add the following to .editorconfig:

```
[*.cs]
csharp_new_line_before_open_brace = all:warning
```

2. Open a .cs file and hit Ctrl+K and Ctrl+D to format the code.
3. The braces are formatted to use JavaScript style where they are on the same line as the class/method etc.

```
class Foo {
}
```

4. Try values other than `all` and they all produce the same result.

**Comment by madskristensen** [comment]
@jasonmalinowski this sounds like a bug in the .editorconfig VS implementation and not in this extension. Thoughts?

**Comment by jasonmalinowski** [comment]
@madskristensen @RehanSaeed Indeed, this would be a Roslyn issue and should be over at https://github.com/dotnet/roslyn. I'll move it later today unless one of you beats me to it.

**Comment by jasonmalinowski** [comment]
Migrated to dotnet/roslyn to the linked bug. This can be closed @madskristensen.

**Comment by RehanSaeed** [comment]
According to https://github.com/dotnet/roslyn/issues/18010#issuecomment-288192477 `all` is not allowed, so should be removed from intellisense for this setting. What I'm not sure about is what the syntax is to apply one or more of the allowed options:

```
accessors
types
methods
properties
indexers
events
anonymous_methods
control_blocks
anonymous_types
object_collection_array_initalizers
lambdas
local_functions
```

**Comment by madskristensen** [comment]
@jasonmalinowski can you confirm that I should remove `all` as a valid value for the property?

@RehanSaeed I believe you just separate them with a comma

**Comment by MatthewSteeples** [comment]
Can confirm that _all_ as an option does work, as long as you don't specify an indication level
