### ISSUE TITLE
Why there is no "dotnet_sort_system_directives_first" error highlighting.

### ISSUE THREAD

**Issue by Denis535** [madskristensen/EditorConfigLanguage#20]
### Installed product versions
- Visual Studio: VS enterprise 2017
- This extension: 1.17.204

I'm learning editorconfig and I noticed:
Violation of ```dotnet_style_predefined_type_for_locals_parameters_members``` is highlighted.
But violation of ```dotnet_sort_system_directives_first``` not highlighted.

And  question:
I can sort usings via "Remove and Sort Usings". Can I sort but don't remove? Or this is the only one way?

**Comment by Denis535** [comment]
I noticed right now that "Remove and Sort Usings" does not care abount "dotnet_sort_system_directives_first".
Is it ok?

**Comment by madskristensen** [comment]
This extension only provide the language service in the editor when opening .editorconfig files. It doesn't enforce any rules.

**Comment by Denis535** [comment]
Ok, Sorry.

**Comment by madskristensen** [comment]
No worries. The issue has been passed on to the Visual Studio team

**Comment by markw-t** [comment]
For info, @KaseyU has bugs on the Roslyn repo on this here: https://github.com/dotnet/roslyn/issues/17658 and here: https://github.com/dotnet/roslyn/issues/14450
