### ISSUE TITLE
Error Mismatch for validation

### ISSUE THREAD

**Issue by binaryn3xus** [madskristensen/EditorConfigLanguage#25]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 1.17.212

### Description
For certain csharp properties, I am getting an error that does not match what the config text is. See screenshot.

### Steps to recreate
1. Create a new .editorconfig
2. Add 'csharp_prefer_braces' or 'csharp_prefer_simple_default_expression'
3. Wait for validation squiggly to display in green
4. Hover mouse over it and get error "The keyword "csharpprefer_simple_default_expression" is unknown"

### Current behavior
It is showing a mismatch for the value in the error message. When you hover over the validation that is correct, it shows an incorrect name in the error message.

### Expected behavior
Show the correct one. Maybe even fix these two variables at the same time :+1:  :smile: 

![image](https://user-images.githubusercontent.com/1706923/30704301-4c44761a-9ec0-11e7-817b-0dbdfffa5ea7.png)

**Comment by madskristensen** [comment]
@kuhlenh are these valid and are there more new ones that I need to know about?

**Comment by binaryn3xus** [comment]
I cant speak for the validity of these by the way. I am working off an example file provided by this blog post... https://kent-boogaart.com/blog/editorconfig-reference-for-c-developers 

Is there an official list anywhere? :smile:

**Comment by kuhlenh** [comment]
@JoshuaGarrison27  The official supported rules are here: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference.

@madskristensen We've added a couple more since August that I need to update, and I will get to that soon. It's on my to-do to edit your list of valid rules to match the official documentation!

**Comment by binaryn3xus** [comment]
@kuhlenh Thank you for the reference link.

According to this, both of these keywords are supported.

**Comment by binaryn3xus** [comment]
Awesome. Thanks @madskristensen

**Comment by madskristensen** [comment]
@JoshuaGarrison27 I've released an updated version to the VS Marketplace

**Comment by binaryn3xus** [comment]
Version 1.17.215 correct? If so, I still have the problem with `csharp_prefer_braces`

I saw the commit (6fa28a9) where you added it. But it looks like it was removed in your 'Fixed Merge' (65d966d).

Am I misinterpreting something here?

**Comment by madskristensen** [comment]
You're right. Committing the changes and making a new release

**Comment by binaryn3xus** [comment]
Perfect. Updated and it works now. Thank you for the quick responses and help in this! Love this tool. Just now getting into using .editorconfig.

**Comment by binaryn3xus** [comment]
Awesome. Thanks. That worked. I found some more issues but I may just fork your project and submit a pull request if that is okay.

**Comment by madskristensen** [comment]
Of course. A PR would be great 👍
