### ISSUE TITLE
Roslyn.editorconfig parse failure

### ISSUE THREAD

**Issue by nnpcYvIVl** [madskristensen/EditorConfigLanguage#4]
### Installed product versions
- Visual Studio: 2017 RC
- This extension: 1.10.133

### Description
The Roslyn editorconfig file fails to parse.

### Steps to recreate
Download this file and open in VS: https://github.com/dotnet/roslyn/blob/master/.editorconfig

### Current behavior
EC104	A severity must be specified.
EC114	"all" is not a valid value for the "csharp_new_line_before_open_brace" property"

### Expected behavior
I am assuming that since Microsoft made the file it is correct. Is the parser wrong or is their file incorrect?

**Comment by madskristensen** [comment]
Where did you find the value "all"? I thought all the Roslyn properties could be only "true" or "false".

**Comment by nnpcYvIVl** [comment]
It's from the editorconfig in Microsoft's roslyn repository: https://github.com/dotnet/roslyn/blob/master/.editorconfig

csharp_style_throw_expression = true:suggestion
csharp_style_conditional_delegate_call = true:suggestion

\# Newline settings
**csharp_new_line_before_open_brace = all**
csharp_new_line_before_else = true
csharp_new_line_before_catch = true

**Comment by nnpcYvIVl** [comment]
After speaking with Microsoft it appears that rules without a severity are legal.

For example:
dotnet_sort_system_directives_first = true
csharp_new_line_before_open_brace = all
csharp_new_line_before_else = true
csharp_new_line_before_catch = true
csharp_new_line_before_finally = true
csharp_new_line_before_members_in_object_initializers = true
csharp_new_line_before_members_in_anonymous_types = true

Can you make these properties not throw the EC104 error?

**Comment by madskristensen** [comment]
@nnpcYvIVl That should be fixed in version 1.11 that got published to the VS Marketplace a few days ago. Can you get that version and confirm it works correctly?

You can also get the latest nightly build with extra goodness here http://vsixgallery.com/extension/1209461d-57f8-46a4-814a-dbe5fecef941/

**Comment by nnpcYvIVl** [comment]
It works great, thanks!
