### ISSUE TITLE
csharp_preferred_modifier_order setting is not recognized

### ISSUE THREAD

**Issue by olegsych** [madskristensen/EditorConfigLanguage#40]
### Installed product versions
- Visual Studio: 2017 Community 15.5.5
- This extension: 1.17.233

### Description
The [csharp_preferred_modifier_order](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#a-namenormalizemodifiersmodifier-preferencesa) setting introduced in Visual Studio 15.5 is not recognized by the language service.

### Steps to recreate
1. Add a new `.editorconfig` to a Visual Studio solution
2. Add a `csharp_preferred_modifier_order` setting to the `.editorconfig`
```
csharp_preferred_modifier_order = public,private,protected,internal,static,extern,new,virtual,abstract,sealed,override,readonly,unsafe,volatile,async:error
```

### Current behavior
- The `csharp_preferred_modifier_order` setting is underlined with a green squiggly. 
- The tooltip says `EC112. The keyword csharppreferred_modifier_order is unknown`. Note the missing underscore between `csharp` and `preferred`.

### Expected behavior
- `csharp_preferred_modifier_order` setting is recognized by the language service; 
- Supported modifiers (`public`, `virtual`, `async`, etc.) are displayed in the auto-completion list when editing the setting value.
- Supported severities (`error`, `none`, etc.) are displayed in the auto-completion list when editing setting value

**Comment by MaceWindu** [comment]
same for csharp_style_deconstructed_variable_declaration

**Comment by Gav-Brown** [comment]
Full list:

1. dotnet_style_require_accessibility_modifiers
2. csharp_preferred_modifier_order
3. dotnet_prefer_inferred_tuple_names
4. dotnet_prefer_inferred_anonymous_type_member_names
5. csharp_style_deconstructed_variable_declaration
6. csharp_style_pattern_local_over_anonymous_function

As a side note, Visual Studio Code Style Options in the UI also has:

1. IDE0032:Prefer auto properties
2. IDE0041:Prefer 'is null' over 'object.ReferenceEquals(..., null)'

Which also don't appear here, but Microsoft also don't document them, see
https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference

**Comment by MaceWindu** [comment]
Checked mentioned here options with latest version of extension.

No squiggles:
- csharp_preferred_modifier_order
- dotnet_style_require_accessibility_modifiers
- dotnet_prefer_inferred_tuple_names
- csharp_style_pattern_local_over_anonymous_function
- dotnet_style_prefer_inferred_anonymous_type_member_names

Squiggles:
 - csharp_style_deconstructed_variable_declaration

dotnet_prefer_inferred_anonymous_type_member_names is a typo in MS documentation, and should be dotnet_style_prefer_inferred_anonymous_type_member_names. BTW, they use both names in linked document.

So, for me it looks like only csharp_style_deconstructed_variable_declaration requires fix

**Comment by Gav-Brown** [comment]
@MaceWindu Thanks, I agree no squiggles but no auto-completion or intellisense either.

**Comment by MaceWindu** [comment]
Also checked roslyn code and I think:
IDE0032 - dotnet_style_prefer_auto_properties
IDE0041 - dotnet_style_prefer_is_null_check_over_reference_equality_method
both don't give squiggles to me

**Comment by MaceWindu** [comment]
@Gav-Brown ah, maybe you are right. Didn't checked it

**Comment by Gav-Brown** [comment]
Thanks for looking up the IDE rule names. Nice investigative work!

**Comment by Gav-Brown** [comment]
I also (MS) had typo in dotnet_style_prefer_inferred_tuple_names

**Comment by Gav-Brown** [comment]
@MaceWindu It appears the squiggles come and go. You need to restart VS to get them to appear and then they only appear on first invalid name, So you need to comment them out one by one to detect them or check auto-completion list for the 8 missing rules above.

**Comment by Gav-Brown** [comment]
Just for info. If you turn on `Show undocumented properties` auto completion gives you a set of other available properties. I assume MS/Roslyn team should add the documentation for these.

csharp_indent_block_contents
csharp_indent_braces
csharp_space_after_colon_in_inheritance_clause
csharp_space_after_comma
csharp_space_after_dot
csharp_space_after_semicolon_in_for_statement
csharp_space_around_binary_operators
csharp_space_around_declaration_statements
csharp_space_before_colon_in_inheritance_clause
csharp_space_before_comma
csharp_space_before_dot
csharp_space_before_open_square_brackets
csharp_space_before_semicolon_in_for_statement
csharp_space_between_empty_square_brackets
csharp_space_between_method_call_empty_parameter_list_parentheses
csharp_space_between_method_call_name_and_opening_parenthesis
csharp_space_between_method_declaration_empty_parameter_list_parentheses
csharp_space_between_method_declaration_name_and_open_parenthesis
csharp_space_between_square_brackets

**Comment by madskristensen** [comment]
cc @kuhlenh
