### ISSUE TITLE
Dotnet snippet triggers warning

### ISSUE THREAD

**Issue by cremor** [madskristensen/EditorConfigLanguage#41]
### Installed product versions
- Visual Studio: 2017 Enterprise 15.6.3
- This extension: 1.17.237

### Description
The included snippet "Dotnet code style settings" triggers a warning because it contains a space in the globbing pattern `[*.{cs, vb}]`.

### Steps to recreate
1. Add a new editorconfig file
2. Use the snippet "Dotnet code style settings"

### Current behavior
The warning EC117 "Spaces in globbing patterns are allowed, but are often the result of a typo. Make sure the globbing pattern is accurate." is shown.

### Expected behavior
The snippet shouldn't contain the space in the globbing pattern so that no warning is triggered.

**Comment by MisinformedDNA** [comment]
@madskristensen This is fixed and can be closed.
