### ISSUE TITLE
dotnet_style_prefer_is_null_check_over_reference_equality_method is unknown

### ISSUE THREAD

**Issue by meziantou** [madskristensen/EditorConfigLanguage#44]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.17.237

### Description

`dotnet_style_prefer_is_null_check_over_reference_equality_method` is unknown. This keyword is defined in the documentation (https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference)

More generally I think the list should be updated to support VS15.7 features.

### Current behavior

A warning is present

### Expected behavior

It should be supported

**Comment by sharwell** [comment]
Fixed by #46

**Comment by tonyhallett** [comment]
@madskristensen @sharwell this can be closed
