### ISSUE TITLE
dotnet_style_require_accessibility_modifiers is unknown

### ISSUE THREAD

**Issue by sc1ent** [madskristensen/EditorConfigLanguage#48]
### Installed product versions
- Visual Studio: 2017 Enterprise 15.7.6
- This extension: 1.17.237

### Description
`dotnet_style_require_accessibility_modifiers` is unknown. This keyword is defined in the [documentation](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference)

### Current behavior
EC112 warning is present

### Expected behavior
No warning is present. It is supported by the extension.

**Comment by tonyhallett** [comment]
@madskristensen this can be closed
