### ISSUE TITLE
[Feature Request] Create editorconfig from my current formatting settings

### ISSUE THREAD

**Issue by jakubsuchybio** [madskristensen/EditorConfigLanguage#6]
### Installed product versions
- Visual Studio: [2017 Community]
- This extension: [example 1.15.194]

### Description
It would be awesome, if I could create the whole .editorconfig file from my current settings in Visual Studio. It would save a lot of work.

**Comment by xt0rted** [comment]
Would love to have an export settings feature as well as it makes bootstrapping a config much easier.

**Comment by irontoby** [comment]
Not exactly what you're looking for but Microsoft's [IntelliCode Extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.VSIntelliCode) will generate an `.editorconfig` by detecting the conventions in your existing codebase.

**Comment by jakubsuchybio** [comment]
Yes, it can generate .editorconfig by learning from code.
But I set my coding preferences in settings and I want to generate .editorconfig from that, so that my teammates can leverage same coding style without of needing changing their default settings. That is what .editorconfig is for.

**Comment by cremor** [comment]
Visual Studio 2019 will have the feature to export the current IDE settings as a .editorconfig file. From the  [preview release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview):

> Export editor settings to an Editorconfig file through Tools > Options > Text Editor > C# > Code Style with the button "Generate .editorconfig file from settings".

**Comment by jakubsuchybio** [comment]
Oh yeah! I totally forgot about that. Thanks.
Closing this then :)
