### ISSUE TITLE
Incorrect EC114 warnings for "local" value

### ISSUE THREAD

**Issue by djosla26** [madskristensen/EditorConfigLanguage#60]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.17.246

### Description
Displaying warning EC114 - "local" is not valid value in the following two cases:
dotnet_naming_symbols.constants.applicable_kinds = field, local
dotnet_naming_symbols.locals_and_parameters.applicable_kinds = parameter, local

### Steps to recreate
1. Add to you .editorconfig file
dotnet_naming_symbols.constants.applicable_kinds = field, local
dotnet_naming_symbols.locals_and_parameters.applicable_kinds = parameter, local
2. Build your solution and check warnings

### Current behavior
Displaying warning EC114 - "local" is not valid value for the following:
dotnet_naming_symbols.constants.applicable_kinds = field, local
dotnet_naming_symbols.locals_and_parameters.applicable_kinds = parameter, local

### Expected behavior
Don't display EC114 warning for local value of dotnet_naming_symbols.constants.applicable_kinds and 
dotnet_naming_symbols.locals_and_parameters.applicable_kinds (check https://github.com/dotnet/roslyn/blob/master/.editorconfig).

![warningec114](https://user-images.githubusercontent.com/46377716/50694265-b2c5d280-1039-11e9-87c8-26e5c2913a11.JPG)

**Comment by madskristensen** [comment]
It looks like it is the space between the comma and `local` that is not supported. What happens if you remove the space so it reads `parameter,local` instead?

**Comment by djosla26** [comment]
Still getting the same warnings.

![warningec114_withoutspace](https://user-images.githubusercontent.com/46377716/50702012-e7448900-104f-11e9-9c41-d9912dc7b4ff.JPG)

**Comment by sharwell** [comment]
Fixed by #53

**Comment by tonyhallett** [comment]
@sharwell @madskristensen  this can be closed
