### ISSUE TITLE
Incorrect EC114 warnings for "local_function" value in VS2017

### ISSUE THREAD

**Issue by djosla26** [madskristensen/EditorConfigLanguage#61]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.17.246

### Description
Displaying warning EC114 - "local_function" is not valid value in the following case:
   dotnet_naming_symbols.local_functions.applicable_kinds = local_function

### Steps to recreate
1. Add to you .editorconfig file
   dotnet_naming_symbols.local_functions.applicable_kinds = local_function
2. Check warnings

### Current behavior
Displaying warning EC114 - "local_function" is not valid value for   dotnet_naming_symbols.local_functions.applicable_kinds = local_function

![warningec114_for_local_function](https://user-images.githubusercontent.com/46377716/51166164-de02ba00-18a2-11e9-9c97-901992604e0a.JPG)

### Expected behavior
Don't display EC114 warning for local_function value of dotnet_naming_symbols.local_functions.applicable_kinds (check https://github.com/dotnet/roslyn/blob/master/.editorconfig).

**Comment by sharwell** [comment]
Fixed by #53

**Comment by tonyhallett** [comment]
@sharwell @madskristensen  this can be closed
