### ISSUE TITLE
dotnet_separate_import_directive_groups is unknown

### ISSUE THREAD

**Issue by AlexanderTaeschner** [madskristensen/EditorConfigLanguage#64]
### Installed product versions
- Visual Studio: Community 2017 Version 15.9.7
- This extension: 1.17.246

### Description
`dotnet_separate_import_directive_groups` is unknown. This keyword is defined in the [documentation](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference).

### Current behavior
EC112 warning is displayed.

### Expected behavior
No warning is present. It is supported by the extension.

**Comment by Metrowerks** [comment]
Why were this problem closed? I got the error too. I have VS 2017 15.9.11.
