### ISSUE TITLE
Current Extension Does Not Include Current Schema From Master Branch

### ISSUE THREAD

**Issue by tonyhallett** [madskristensen/EditorConfigLanguage#65]
### Installed product versions
- Visual Studio: 2017 Community 15.9.7
- This extension: 1.17.246

### Description
In the Schema folder inside the extension folder
\AppData\Local\Microsoft\VisualStudio\15.0_fa800525\Extensions\lu0luhxe.b0c EditorConfig.json is not up to date.
For instance this is the applicable kinds
`{
"name": "dotnet_naming_symbols.<naming_symbols_title>.applicable_kinds",
"description": "Application kinds.",
"values": [ "*", "class", "struct", "interface", "enum", "property", "method", "field", "event", "delegate", "parameter" ],
"defaultValue": [ "*" ],
"multiple": true,
"documentationLink": "https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions"
},
`

### Steps to recreate
Install the extension

### Current behavior
Due to the missing applicable_kinds getting Incorrect EC114 warnings as per [Issue 61](https://github.com/madskristensen/EditorConfigLanguage/issues/61) and [Issue 60](https://github.com/madskristensen/EditorConfigLanguage/issues/60)

### Expected behavior
`{
      "name": "dotnet_naming_symbols.<naming_symbols_title>.applicable_kinds",
      "description": "Application kinds.",
      "values": [ "*", "namespace", "class", "struct", "interface", "enum", "property", "method", "field", "event", "delegate", "parameter", "type_parameter", "local", "local_function" ],
      "defaultValue": [ "*" ],
      "multiple": true,
      "documentationLink": "https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions"
    },
`
as per [merged pull request 53 ](https://github.com/madskristensen/EditorConfigLanguage/pull/53)

**Comment by madskristensen** [comment]
I'll make a fresh release to the Marketplace. Stay tuned...

**Comment by madskristensen** [comment]
It's now live
