### ISSUE TITLE
Current Extension Does Not Include Current Schema From Master Branch

### ISSUE THREAD

**Issue by tonyhallett** [madskristensen/EditorConfigLanguage#68]
### Installed product versions
Visual Studio: 2017 Community 15.9.7
This extension: 1.17.258

### Description
Same problem [as before](https://github.com/madskristensen/EditorConfigLanguage/issues/65)

e.g private_protected applicable accessibility is not present

**Comment by Regenhardt** [comment]
I have the same problem. But in master, `private_protected` is already included. Just need a VS Marketplace release, there's still 1.17.258 online.

**Comment by madskristensen** [comment]
I'll make the release now

**Comment by madskristensen** [comment]
Done
