### ISSUE TITLE
Intellisense throws exception at position 0.

### ISSUE THREAD

**Issue by mdschweda** [madskristensen/EditorConfigLanguage#7]
### Installed product versions
- Visual Studio: 2017
- This extension: 1.15.194

### Description
Intellisense throws exception at position 0.

### Steps to recreate
1. Add new line at start of file
2. Place cursor at Ln 1, Col 1
3. Press <kbd>Ctrl</kbd> + <kbd>Space</kbd>

### Current behavior
"Speciefied argument is out of range of valid values. Parameter name: position"

### Expected behavior
Suggest "root"

**Comment by madskristensen** [comment]
Thanks for reporting this.
