### ISSUE TITLE
Support for csharp_using_directive_placement

### ISSUE THREAD

**Issue by xt0rted** [madskristensen/EditorConfigLanguage#70]
A new setting of `csharp_using_directive_placement` was announced as part of 16.1 Preview 3 earlier today. The options seem to be `inside_namespace` and `outside_namespace`.

https://devblogs.microsoft.com/visualstudio/visual-studio-2019-version-16-1-preview-3/

**Comment by Advanium** [comment]
Is there a documentation link yet? I can't seem to find it. It [already shipped](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#--visual-studio-2019-version-161) in Visual Studio 2019 16.1 (see .NET section).

In the meantime I'll point it to [Formatting conventions](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-formatting-conventions#c-formatting-settings), as the other using directive related settings are located there.

**Comment by cremor** [comment]
No, it's one of many settings (MicrosoftDocs/visualstudio-docs#1070) that are currently not documented.
